### PR TITLE
Food Donation Page Functionality and Home Screen

### PR DESCRIPTION
**Pull request by jreese14**
- Added the backend functionality for posting food donation 
- Did the UI for the food donation page
- Added a basic home screen with navigation bar

### CODE REVIEW

**Comment by laothomas01** [comment]
-i think FoodDonationItems should be named to something more. We have a fooddonationitem object then fooddonationitems object which can be renamed to ListOfDonations. 
-for future uses, I think FoodDonationItem should extend the User object so we know whose donation belongs to who. 
-good commenting
-good code organization

**Comment by laothomas01** [comment]
-code organization is good
-good code documentation
-I think FoodDonationItems should be renamed to something like ListOfFoodDonations. 
-FoodDonationItem might have to extend the User object because so users know whose food donation belongs to who.

**Review by laothomas01 — APPROVED** [review]
-code organization is good
-good code documentation
-I think FoodDonationItems should be renamed to something like ListOfFoodDonations.
-how do users know which food donation belongs to them?

**Review by jessicafeliciaa — COMMENTED** [review]
The code looks good and organized.
The UI for Food donation page looks good.

**Review by yingzhengyu — APPROVED** [review]

**Review by nicholasdave12 — APPROVED** [review]
The code looks well documented. It easy for me to add some features.

I've give a temporary Logout button on the activity_main.xml, so that we can logout temporarily when remember me features enabled.

**Review by yingzhengyu — APPROVED** [review]

**Review by yingzhengyu — COMMENTED** [review]
Well organized code and easy to follow! Only critique I can give is several extra spaces or lines so I would just delete them if it were me but it looks great!

**Pull request merged**
